version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 655522631902.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...          
      - docker build -t github1:latest .
      - docker tag github:latest 655522631902.dkr.ecr.us-east-1.amazonaws.com/github1:latest      
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push 655522631902.dkr.ecr.us-east-1.amazonaws.com/github1:latest
