name: Deploy to ECR

on:
  push:
    branches:
      - main  # Adjust to your branch for deployment
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAZRIBRSDPJCFSA24U
          aws-secret-access-key: gLHztsBg2iwy8nrcI3+CgFZMFXSA/N72SXF1A81D
          aws-region: us-east-1  # Adjust your region

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          echo Logging into ECR
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 643212820363.dkr.ecr.us-east-1.amazonaws.com

      # Build and tag the Docker image
      - name: Build Docker Image
        run: |
          echo Starting build at `date`
          echo Building the Docker image...
          docker build -t github:latest .
          docker tag github:latest 643212820363.dkr.ecr.us-east-1.amazonaws.com/github:latest

      # Push the image to ECR
      - name: Push to ECR
        run: |
          echo Pushing the Docker image...
          docker push 643212820363.dkr.ecr.us-east-1.amazonaws.com/github:latest

      # Complete build process
      - name: Complete Build
        run: |
          echo Completed build at `date`
