name: Deploy to ECR

on:
  push:
    branches:
      - main  # Adjust to your branch for deployment
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
           aws-access-key-id: AKIAZRIBRSDPJCFSA24U
          aws-secret-access-key: gLHztsBg2iwy8nrcI3+CgFZMFXSA/N72SXF1A81D
          aws-region: us-east-1  # Adjust your region
          
     version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 655522631902.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Starting build at `date`
      - echo Building the Docker image...          
      - docker build -t github:latest .
      - docker tag github:latest 655522631902.dkr.ecr.us-east-1.amazonaws.com/github:latest      
  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push 655522631902.dkr.ecr.us-east-1.amazonaws.com/github:latest

        run: |
          echo Completed build at `date`
