name: Deploy to ECR

on:
  push:
    branches:
      - main  # Adjust to your branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAZRIBRSDPJGXYXKEJ
          aws-secret-access-key: MwqrkrPt57UYd0aTGM4zPuSPQM45tWUeLQFLv4Wd
          aws-region: us-east-1  # Adjust your region

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 655522631902.dkr.ecr.us-east-1.amazonaws.com

      # Build and tag the Docker image
      - name: Build Docker Image
        run: |
          docker build -t github .
          docker tag github:latest 655522631902.dkr.ecr.us-east-1.amazonaws.com/github:latest

      # Push the image to ECR
      - name: Push to ECR
        run: |
          docker push 655522631902.dkr.ecr.us-east-1.amazonaws.com/github:latest
