name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: 643212820363.dkr.ecr.us-east-1.amazonaws.com/github:latest

      - name: Log in to Amazon ECR
        uses: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 643212820363.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t github .
          docker tag github:latest 643212820363.dkr.ecr.us-east-1.amazonaws.com/github:latest

      - name: Push Docker image to ECR
        run: |
          docker push 643212820363.dkr.ecr.us-east-1.amazonaws.com/github:latest
